manipulator_dir: xml_models/manipulators/sequential
reset_keyframe: initial_state
recorder:
  target_class: BasicRecorder
  track_cam_name: tracking
  fig_height: 800
  fig_width: 800
  fps: 60
  videoname: output.mp4
  videcodec: mp4v
  dataset_dir: ???
planner:
  target_class: JointPositionPlanner
  duration: 5.0
  timestep: -1.0
  displacements:
  - 0.2
  - 1.4
  - 0.6
  - 3.141592653589793  # 1π
  - 0.0
  - 25.1327412287  # 8π
  pos_offset: ???
controller:
  target_class: LinearQuadraticRegulator
  state_space:
    epsilon: 1.0e-08
    centered: true
  input_gain:
  - 10.0
  - 10.0
  - 10.0
  - 10000.0
  - 10000.0
  - 10000.0
