manipulator_dir: xml_models/manipulators/sequential
reset_keyframe: initial_state
recorder:
  target_class: BasicRecorder
  track_cam_name: tracking
  fig_height: 800
  fig_width: 800
  #fps: 60
  videoname: output.mp4
  videcodec: mp4v
planner:
  target_class: JointPositionPlanner
  displacements:
  - 0.2
  - 1.4
  - 0.6
  - 3.141592653589793  # 1π
  - 0.0
  - 25.1327412287  # 8π
controller:
  target_class: LinearQuadraticRegulator
  state_space:
    epsilon: 1.0e-08
    centered: true
  input_gain:
  - 10.0
  - 10.0
  - 10.0
  - 10000.0
  - 10000.0
  - 10000.0
duration: 3.0
fps: 60