[xml]
  system_file = "_obj_w_links.xml"
  rel_root_path = "./xml_models"

[simu_time]
  duration = 2
  fps = 60
  timestep = -1

[track_cam]
  name = "tracking"
  height = 800
  width = 800
  codec = "mp4v"
  output_file = "output.mp4"

[trajectory]
  planner = "spline_5"
  init_frame = "init_pose"
  dqpos = [
    0.2,
    0.4,
    0.6,
    3.14159265359,  # 1.0 x π
    0.94247779607,  # 0.3 x π
    4.71238898039,  # 1.5 x π
  ]

[lqr]
  epsilon = 0.000001  # Differential displacement
  centered = true  # Use the centred differentiation; false for the forward one
  input_weights = [1, 1, 1, 1_000_000, 1_000_000, 1_000_000]
#  input_weights = [1, 1, 1, 1, 1, 1]

[wisp_input]
  input_file = "transforms.json"

